config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  get '/find', to: 'posts#find_get'
  post '/find', to: 'posts#find'
  get '/my_roles', to: 'roles#my_roles'

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    puts user

    can :read, Post

    return unless user.present?

    can :manage, Post, creator: user.id

    return unless user.role_id == 1

    can :manage, Post
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :roles
  # belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # class UserAbility
  #   include CanCan::Ability
  #
  #   def initialize(user)
  #     can :read, Post
  #
  #     return unless user.present?
  #
  #     can :manage, Post, creator: user.id
  #   end
  # end

  # class AdminAbility
  #   include CanCan::Ability
  #
  #   def initialize(_user)
  #     can :read, Post
  #     can :manage, Post
  #   end
  # end
  #
  # def current_ability
  #   @current_ability ||= if !current_user.nil? && current_user.role_id == 1
  #                          AdminAbility.new(current_user)
  #                        else
  #                          UserAbility.new(current_user)
  #                        end
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new]

  load_and_authorize_resource except: %i[new create]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  def find_get
    render :find
  end

  def find
    if (@post = Post.find_by(title: params[:title]))
      render @post
    else
      render 'missing_post'
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.creator = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :creator)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def my_roles; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Button
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p.notice= notice
    p.alert= alert
    = yield

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, 'error')} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit

app/views/posts/_post.html.slim
p
  strong Title:
  = @post.title

p
  strong Body:
  = @post.body

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

=> link_to 'Show', @post
'|
=< link_to 'Back', posts_path

app/views/posts/find.html.slim
h2 Find a post by its title

= link_to 'Back', posts_path
br
br

div data-controller="finder"
  = form_with url: "/find", html: { data: { remote: true, action: "ajax:success->finder#find" } } do |form|
    = form.text_field :title, data: { target: "finder.title" }
    = form.submit "Find post"

  div data-target="finder.foundPost"
    /-if @post != nil
      = render @post

app/views/posts/index.html.slim
h1 Listing posts

-if user_signed_in?
  p Hello, #{current_user.email}
  = link_to 'Log out', destroy_user_session_path, method: :delete
  br
  = link_to 'View roles', '/my_roles'
-else
  = link_to 'Log in', new_user_session_path
  |  or #{link_to 'Register', new_user_registration_path}
br
br

table
  thead
    tr
      th Title
      th Body
      th
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = post.body
        td = link_to 'Show', post
        -if can? :manage, post
          td = link_to 'Edit', edit_post_path(post)
          td = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Post', new_post_path
br
= link_to 'Find a post', find_path

app/views/posts/missing_post.html.slim
p No such post, sorry!

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p
  strong Title:
  = @post.title

p
  strong Body:
  = @post.body

-if can? :manage, @post
  => link_to 'Edit', edit_post_path(@post)
  '|
=< link_to 'Back', posts_path

app/views/roles/my_roles.html.slim
h2 View your roles

-if current_user.roles.any?
  - current_user.roles.each do |role|
    p
      =role.name
-else
  p Oops! You have no roles! That's embarassing...